// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkgeecayuhjehpzmevga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrZ2VlY2F5dWhqZWhwem1ldmdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjE4MjksImV4cCI6MjA2Nzc5NzgyOX0.yk-1igefASmuZ8Vghhm66nZWdjQalRklgcZjXHbaYgY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});